version: "3.8"

services:
  jenkins:
    build: 
      context: .
      dockerfile: jen.Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: always

  ai-agent:
    image: ai_agent
    container_name: ai1
    ports:
      - "5001:5001"
    restart: always

volumes:
  jenkins_home:
